# Generated by Django 4.2.3 on 2023-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
    ]
