# Generated by Django 4.2.3 on 2023-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
